/**
 * EjbcaWS.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package org.ejbca.core.protocol.ws;

public interface EjbcaWS extends java.rmi.Remote {
    public void caCertResponse(java.lang.String arg0, byte[] arg1, byte[][] arg2, java.lang.String arg3) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public byte[] caRenewCertRequest(java.lang.String arg0, byte[][] arg1, boolean arg2, boolean arg3, boolean arg4, java.lang.String arg5) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public org.ejbca.core.protocol.ws.CertificateResponse certificateRequest(org.ejbca.core.protocol.ws.UserDataVOWS arg0, java.lang.String arg1, int arg2, java.lang.String arg3, java.lang.String arg4) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.UserDoesntFullfillEndEntityProfile, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public org.ejbca.core.protocol.ws.RevokeStatus checkRevokationStatus(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public void createCRL(java.lang.String arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.ApprovalRequestExpiredException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public org.ejbca.core.protocol.ws.CertificateResponse crmfRequest(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public void customLog(int arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, org.ejbca.core.protocol.ws.Certificate arg4, java.lang.String arg5) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public org.ejbca.core.protocol.ws.Certificate[] cvcRequest(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.CertificateExpiredException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.SignRequestException, org.ejbca.core.protocol.ws.UserDoesntFullfillEndEntityProfile, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public boolean deleteUserDataFromSource(java.lang.String[] arg0, java.lang.String arg1, boolean arg2) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.MultipleMatchException, org.ejbca.core.protocol.ws.UserDataSourceException;
    public void editUser(org.ejbca.core.protocol.ws.UserDataVOWS arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.UserDoesntFullfillEndEntityProfile, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public boolean existsHardToken(java.lang.String arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException;
    public org.ejbca.core.protocol.ws.UserDataSourceVOWS[] fetchUserData(java.lang.String[] arg0, java.lang.String arg1) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.UserDataSourceException;
    public org.ejbca.core.protocol.ws.Certificate[] findCerts(java.lang.String arg0, boolean arg1) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException;
    public org.ejbca.core.protocol.ws.UserDataVOWS[] findUser(org.ejbca.core.protocol.ws.UserMatch arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.IllegalQueryException;
    public org.ejbca.core.protocol.ws.TokenCertificateResponseWS[] genTokenCertificates(org.ejbca.core.protocol.ws.UserDataVOWS arg0, org.ejbca.core.protocol.ws.TokenCertificateRequestWS[] arg1, org.ejbca.core.protocol.ws.HardTokenDataWS arg2, boolean arg3, boolean arg4) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.HardTokenExistsException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.ApprovalRequestExpiredException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.UserDoesntFullfillEndEntityProfile, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException, org.ejbca.core.protocol.ws.ApprovalRequestExecutionException;
    public org.ejbca.core.protocol.ws.NameAndId[] getAuthorizedEndEntityProfiles() throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException;
    public org.ejbca.core.protocol.ws.NameAndId[] getAvailableCAs() throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException;
    public org.ejbca.core.protocol.ws.NameAndId[] getAvailableCAsInProfile(int arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException;
    public org.ejbca.core.protocol.ws.NameAndId[] getAvailableCertificateProfiles(int arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException;
    public org.ejbca.core.protocol.ws.Certificate getCertificate(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public java.lang.String getEjbcaVersion() throws java.rmi.RemoteException;
    public org.ejbca.core.protocol.ws.HardTokenDataWS getHardTokenData(java.lang.String arg0, boolean arg1, boolean arg2) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.ApprovalRequestExpiredException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.HardTokenDoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException, org.ejbca.core.protocol.ws.ApprovalRequestExecutionException;
    public org.ejbca.core.protocol.ws.HardTokenDataWS[] getHardTokenDatas(java.lang.String arg0, boolean arg1, boolean arg2) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public org.ejbca.core.protocol.ws.Certificate[] getLastCAChain(java.lang.String arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public org.ejbca.core.protocol.ws.Certificate[] getLastCertChain(java.lang.String arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException;
    public int getPublisherQueueLength(java.lang.String arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException;
    public int isApproved(int arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.ApprovalRequestExpiredException, org.ejbca.core.protocol.ws.ApprovalException;
    public boolean isAuthorized(java.lang.String arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException;
    public void keyRecoverNewest(java.lang.String arg0) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public org.ejbca.core.protocol.ws.CertificateResponse pkcs10Request(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public org.ejbca.core.protocol.ws.KeyStore pkcs12Req(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public void republishCertificate(java.lang.String arg0, java.lang.String arg1) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.PublisherException, org.ejbca.core.protocol.ws.CADoesntExistsException;
    public void revokeCert(java.lang.String arg0, java.lang.String arg1, int arg2) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.AlreadyRevokedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public void revokeCertBackdated(java.lang.String arg0, java.lang.String arg1, int arg2, java.lang.String arg3) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.RevokeBackDateNotAllowedForProfileException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.AlreadyRevokedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.DateNotValidException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public void revokeToken(java.lang.String arg0, int arg1) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.AlreadyRevokedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public void revokeUser(java.lang.String arg0, int arg1, boolean arg2) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.AlreadyRevokedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public org.ejbca.core.protocol.ws.KeyStore softTokenRequest(org.ejbca.core.protocol.ws.UserDataVOWS arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.ApprovalException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.UserDoesntFullfillEndEntityProfile, org.ejbca.core.protocol.ws.CADoesntExistsException, org.ejbca.core.protocol.ws.WaitingForApprovalException;
    public org.ejbca.core.protocol.ws.CertificateResponse spkacRequest(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2, java.lang.String arg3, java.lang.String arg4) throws java.rmi.RemoteException, org.ejbca.core.protocol.ws.EjbcaException, org.ejbca.core.protocol.ws.AuthorizationDeniedException, org.ejbca.core.protocol.ws.NotFoundException, org.ejbca.core.protocol.ws.CADoesntExistsException;
}
