
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.703-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "AlreadyRevokedException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class AlreadyRevokedException_Exception extends Exception {
    
    private cl.c2c.ejbca.AlreadyRevokedException alreadyRevokedException;

    public AlreadyRevokedException_Exception() {
        super();
    }
    
    public AlreadyRevokedException_Exception(String message) {
        super(message);
    }
    
    public AlreadyRevokedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AlreadyRevokedException_Exception(String message, cl.c2c.ejbca.AlreadyRevokedException alreadyRevokedException) {
        super(message);
        this.alreadyRevokedException = alreadyRevokedException;
    }

    public AlreadyRevokedException_Exception(String message, cl.c2c.ejbca.AlreadyRevokedException alreadyRevokedException, Throwable cause) {
        super(message, cause);
        this.alreadyRevokedException = alreadyRevokedException;
    }

    public cl.c2c.ejbca.AlreadyRevokedException getFaultInfo() {
        return this.alreadyRevokedException;
    }
}
