
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.682-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "ApprovalException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class ApprovalException_Exception extends Exception {
    
    private cl.c2c.ejbca.ApprovalException approvalException;

    public ApprovalException_Exception() {
        super();
    }
    
    public ApprovalException_Exception(String message) {
        super(message);
    }
    
    public ApprovalException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ApprovalException_Exception(String message, cl.c2c.ejbca.ApprovalException approvalException) {
        super(message);
        this.approvalException = approvalException;
    }

    public ApprovalException_Exception(String message, cl.c2c.ejbca.ApprovalException approvalException, Throwable cause) {
        super(message, cause);
        this.approvalException = approvalException;
    }

    public cl.c2c.ejbca.ApprovalException getFaultInfo() {
        return this.approvalException;
    }
}
