
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.666-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "ApprovalRequestExpiredException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class ApprovalRequestExpiredException_Exception extends Exception {
    
    private cl.c2c.ejbca.ApprovalRequestExpiredException approvalRequestExpiredException;

    public ApprovalRequestExpiredException_Exception() {
        super();
    }
    
    public ApprovalRequestExpiredException_Exception(String message) {
        super(message);
    }
    
    public ApprovalRequestExpiredException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ApprovalRequestExpiredException_Exception(String message, cl.c2c.ejbca.ApprovalRequestExpiredException approvalRequestExpiredException) {
        super(message);
        this.approvalRequestExpiredException = approvalRequestExpiredException;
    }

    public ApprovalRequestExpiredException_Exception(String message, cl.c2c.ejbca.ApprovalRequestExpiredException approvalRequestExpiredException, Throwable cause) {
        super(message, cause);
        this.approvalRequestExpiredException = approvalRequestExpiredException;
    }

    public cl.c2c.ejbca.ApprovalRequestExpiredException getFaultInfo() {
        return this.approvalRequestExpiredException;
    }
}
