
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.670-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "CADoesntExistsException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CADoesntExistsException_Exception extends Exception {
    
    private cl.c2c.ejbca.CADoesntExistsException caDoesntExistsException;

    public CADoesntExistsException_Exception() {
        super();
    }
    
    public CADoesntExistsException_Exception(String message) {
        super(message);
    }
    
    public CADoesntExistsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CADoesntExistsException_Exception(String message, cl.c2c.ejbca.CADoesntExistsException caDoesntExistsException) {
        super(message);
        this.caDoesntExistsException = caDoesntExistsException;
    }

    public CADoesntExistsException_Exception(String message, cl.c2c.ejbca.CADoesntExistsException caDoesntExistsException, Throwable cause) {
        super(message, cause);
        this.caDoesntExistsException = caDoesntExistsException;
    }

    public cl.c2c.ejbca.CADoesntExistsException getFaultInfo() {
        return this.caDoesntExistsException;
    }
}
