
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.686-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "CesecoreException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CesecoreException_Exception extends Exception {
    
    private cl.c2c.ejbca.CesecoreException cesecoreException;

    public CesecoreException_Exception() {
        super();
    }
    
    public CesecoreException_Exception(String message) {
        super(message);
    }
    
    public CesecoreException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CesecoreException_Exception(String message, cl.c2c.ejbca.CesecoreException cesecoreException) {
        super(message);
        this.cesecoreException = cesecoreException;
    }

    public CesecoreException_Exception(String message, cl.c2c.ejbca.CesecoreException cesecoreException, Throwable cause) {
        super(message, cause);
        this.cesecoreException = cesecoreException;
    }

    public cl.c2c.ejbca.CesecoreException getFaultInfo() {
        return this.cesecoreException;
    }
}
