
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.689-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "CryptoTokenOfflineException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CryptoTokenOfflineException_Exception extends Exception {
    
    private cl.c2c.ejbca.CryptoTokenOfflineException cryptoTokenOfflineException;

    public CryptoTokenOfflineException_Exception() {
        super();
    }
    
    public CryptoTokenOfflineException_Exception(String message) {
        super(message);
    }
    
    public CryptoTokenOfflineException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CryptoTokenOfflineException_Exception(String message, cl.c2c.ejbca.CryptoTokenOfflineException cryptoTokenOfflineException) {
        super(message);
        this.cryptoTokenOfflineException = cryptoTokenOfflineException;
    }

    public CryptoTokenOfflineException_Exception(String message, cl.c2c.ejbca.CryptoTokenOfflineException cryptoTokenOfflineException, Throwable cause) {
        super(message, cause);
        this.cryptoTokenOfflineException = cryptoTokenOfflineException;
    }

    public cl.c2c.ejbca.CryptoTokenOfflineException getFaultInfo() {
        return this.cryptoTokenOfflineException;
    }
}
