
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.675-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "EjbcaException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class EjbcaException_Exception extends Exception {
    
    private cl.c2c.ejbca.EjbcaException ejbcaException;

    public EjbcaException_Exception() {
        super();
    }
    
    public EjbcaException_Exception(String message) {
        super(message);
    }
    
    public EjbcaException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EjbcaException_Exception(String message, cl.c2c.ejbca.EjbcaException ejbcaException) {
        super(message);
        this.ejbcaException = ejbcaException;
    }

    public EjbcaException_Exception(String message, cl.c2c.ejbca.EjbcaException ejbcaException, Throwable cause) {
        super(message, cause);
        this.ejbcaException = ejbcaException;
    }

    public cl.c2c.ejbca.EjbcaException getFaultInfo() {
        return this.ejbcaException;
    }
}
