
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.693-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "IllegalQueryException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class IllegalQueryException_Exception extends Exception {
    
    private cl.c2c.ejbca.IllegalQueryException illegalQueryException;

    public IllegalQueryException_Exception() {
        super();
    }
    
    public IllegalQueryException_Exception(String message) {
        super(message);
    }
    
    public IllegalQueryException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public IllegalQueryException_Exception(String message, cl.c2c.ejbca.IllegalQueryException illegalQueryException) {
        super(message);
        this.illegalQueryException = illegalQueryException;
    }

    public IllegalQueryException_Exception(String message, cl.c2c.ejbca.IllegalQueryException illegalQueryException, Throwable cause) {
        super(message, cause);
        this.illegalQueryException = illegalQueryException;
    }

    public cl.c2c.ejbca.IllegalQueryException getFaultInfo() {
        return this.illegalQueryException;
    }
}
