
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.643-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "NotFoundException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class NotFoundException_Exception extends Exception {
    
    private cl.c2c.ejbca.NotFoundException notFoundException;

    public NotFoundException_Exception() {
        super();
    }
    
    public NotFoundException_Exception(String message) {
        super(message);
    }
    
    public NotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NotFoundException_Exception(String message, cl.c2c.ejbca.NotFoundException notFoundException) {
        super(message);
        this.notFoundException = notFoundException;
    }

    public NotFoundException_Exception(String message, cl.c2c.ejbca.NotFoundException notFoundException, Throwable cause) {
        super(message, cause);
        this.notFoundException = notFoundException;
    }

    public cl.c2c.ejbca.NotFoundException getFaultInfo() {
        return this.notFoundException;
    }
}
