
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.710-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "PublisherException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class PublisherException_Exception extends Exception {
    
    private cl.c2c.ejbca.PublisherException publisherException;

    public PublisherException_Exception() {
        super();
    }
    
    public PublisherException_Exception(String message) {
        super(message);
    }
    
    public PublisherException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PublisherException_Exception(String message, cl.c2c.ejbca.PublisherException publisherException) {
        super(message);
        this.publisherException = publisherException;
    }

    public PublisherException_Exception(String message, cl.c2c.ejbca.PublisherException publisherException, Throwable cause) {
        super(message, cause);
        this.publisherException = publisherException;
    }

    public cl.c2c.ejbca.PublisherException getFaultInfo() {
        return this.publisherException;
    }
}
