
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.707-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "SignRequestException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class SignRequestException_Exception extends Exception {
    
    private cl.c2c.ejbca.SignRequestException signRequestException;

    public SignRequestException_Exception() {
        super();
    }
    
    public SignRequestException_Exception(String message) {
        super(message);
    }
    
    public SignRequestException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SignRequestException_Exception(String message, cl.c2c.ejbca.SignRequestException signRequestException) {
        super(message);
        this.signRequestException = signRequestException;
    }

    public SignRequestException_Exception(String message, cl.c2c.ejbca.SignRequestException signRequestException, Throwable cause) {
        super(message, cause);
        this.signRequestException = signRequestException;
    }

    public cl.c2c.ejbca.SignRequestException getFaultInfo() {
        return this.signRequestException;
    }
}
