
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.677-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "ApprovalRequestExecutionException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class ApprovalRequestExecutionException_Exception extends Exception {
    
    private cl.c2c.ejbca.ApprovalRequestExecutionException approvalRequestExecutionException;

    public ApprovalRequestExecutionException_Exception() {
        super();
    }
    
    public ApprovalRequestExecutionException_Exception(String message) {
        super(message);
    }
    
    public ApprovalRequestExecutionException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ApprovalRequestExecutionException_Exception(String message, cl.c2c.ejbca.ApprovalRequestExecutionException approvalRequestExecutionException) {
        super(message);
        this.approvalRequestExecutionException = approvalRequestExecutionException;
    }

    public ApprovalRequestExecutionException_Exception(String message, cl.c2c.ejbca.ApprovalRequestExecutionException approvalRequestExecutionException, Throwable cause) {
        super(message, cause);
        this.approvalRequestExecutionException = approvalRequestExecutionException;
    }

    public cl.c2c.ejbca.ApprovalRequestExecutionException getFaultInfo() {
        return this.approvalRequestExecutionException;
    }
}
