
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.688-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "CAOfflineException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CAOfflineException_Exception extends Exception {
    
    private cl.c2c.ejbca.CAOfflineException caOfflineException;

    public CAOfflineException_Exception() {
        super();
    }
    
    public CAOfflineException_Exception(String message) {
        super(message);
    }
    
    public CAOfflineException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CAOfflineException_Exception(String message, cl.c2c.ejbca.CAOfflineException caOfflineException) {
        super(message);
        this.caOfflineException = caOfflineException;
    }

    public CAOfflineException_Exception(String message, cl.c2c.ejbca.CAOfflineException caOfflineException, Throwable cause) {
        super(message, cause);
        this.caOfflineException = caOfflineException;
    }

    public cl.c2c.ejbca.CAOfflineException getFaultInfo() {
        return this.caOfflineException;
    }
}
