
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.709-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "CertificateExpiredException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class CertificateExpiredException_Exception extends Exception {
    
    private cl.c2c.ejbca.CertificateExpiredException certificateExpiredException;

    public CertificateExpiredException_Exception() {
        super();
    }
    
    public CertificateExpiredException_Exception(String message) {
        super(message);
    }
    
    public CertificateExpiredException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CertificateExpiredException_Exception(String message, cl.c2c.ejbca.CertificateExpiredException certificateExpiredException) {
        super(message);
        this.certificateExpiredException = certificateExpiredException;
    }

    public CertificateExpiredException_Exception(String message, cl.c2c.ejbca.CertificateExpiredException certificateExpiredException, Throwable cause) {
        super(message, cause);
        this.certificateExpiredException = certificateExpiredException;
    }

    public cl.c2c.ejbca.CertificateExpiredException getFaultInfo() {
        return this.certificateExpiredException;
    }
}
