
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.704-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "DateNotValidException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class DateNotValidException_Exception extends Exception {
    
    private cl.c2c.ejbca.DateNotValidException dateNotValidException;

    public DateNotValidException_Exception() {
        super();
    }
    
    public DateNotValidException_Exception(String message) {
        super(message);
    }
    
    public DateNotValidException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DateNotValidException_Exception(String message, cl.c2c.ejbca.DateNotValidException dateNotValidException) {
        super(message);
        this.dateNotValidException = dateNotValidException;
    }

    public DateNotValidException_Exception(String message, cl.c2c.ejbca.DateNotValidException dateNotValidException, Throwable cause) {
        super(message, cause);
        this.dateNotValidException = dateNotValidException;
    }

    public cl.c2c.ejbca.DateNotValidException getFaultInfo() {
        return this.dateNotValidException;
    }
}
