
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.691-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "EndEntityProfileNotFoundException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class EndEntityProfileNotFoundException_Exception extends Exception {
    
    private cl.c2c.ejbca.EndEntityProfileNotFoundException endEntityProfileNotFoundException;

    public EndEntityProfileNotFoundException_Exception() {
        super();
    }
    
    public EndEntityProfileNotFoundException_Exception(String message) {
        super(message);
    }
    
    public EndEntityProfileNotFoundException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public EndEntityProfileNotFoundException_Exception(String message, cl.c2c.ejbca.EndEntityProfileNotFoundException endEntityProfileNotFoundException) {
        super(message);
        this.endEntityProfileNotFoundException = endEntityProfileNotFoundException;
    }

    public EndEntityProfileNotFoundException_Exception(String message, cl.c2c.ejbca.EndEntityProfileNotFoundException endEntityProfileNotFoundException, Throwable cause) {
        super(message, cause);
        this.endEntityProfileNotFoundException = endEntityProfileNotFoundException;
    }

    public cl.c2c.ejbca.EndEntityProfileNotFoundException getFaultInfo() {
        return this.endEntityProfileNotFoundException;
    }
}
