
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.694-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "HardTokenExistsException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class HardTokenExistsException_Exception extends Exception {
    
    private cl.c2c.ejbca.HardTokenExistsException hardTokenExistsException;

    public HardTokenExistsException_Exception() {
        super();
    }
    
    public HardTokenExistsException_Exception(String message) {
        super(message);
    }
    
    public HardTokenExistsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public HardTokenExistsException_Exception(String message, cl.c2c.ejbca.HardTokenExistsException hardTokenExistsException) {
        super(message);
        this.hardTokenExistsException = hardTokenExistsException;
    }

    public HardTokenExistsException_Exception(String message, cl.c2c.ejbca.HardTokenExistsException hardTokenExistsException, Throwable cause) {
        super(message, cause);
        this.hardTokenExistsException = hardTokenExistsException;
    }

    public cl.c2c.ejbca.HardTokenExistsException getFaultInfo() {
        return this.hardTokenExistsException;
    }
}
