
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.706-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "MultipleMatchException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class MultipleMatchException_Exception extends Exception {
    
    private cl.c2c.ejbca.MultipleMatchException multipleMatchException;

    public MultipleMatchException_Exception() {
        super();
    }
    
    public MultipleMatchException_Exception(String message) {
        super(message);
    }
    
    public MultipleMatchException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MultipleMatchException_Exception(String message, cl.c2c.ejbca.MultipleMatchException multipleMatchException) {
        super(message);
        this.multipleMatchException = multipleMatchException;
    }

    public MultipleMatchException_Exception(String message, cl.c2c.ejbca.MultipleMatchException multipleMatchException, Throwable cause) {
        super(message, cause);
        this.multipleMatchException = multipleMatchException;
    }

    public cl.c2c.ejbca.MultipleMatchException getFaultInfo() {
        return this.multipleMatchException;
    }
}
