
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.701-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "RevokeBackDateNotAllowedForProfileException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class RevokeBackDateNotAllowedForProfileException_Exception extends Exception {
    
    private cl.c2c.ejbca.RevokeBackDateNotAllowedForProfileException revokeBackDateNotAllowedForProfileException;

    public RevokeBackDateNotAllowedForProfileException_Exception() {
        super();
    }
    
    public RevokeBackDateNotAllowedForProfileException_Exception(String message) {
        super(message);
    }
    
    public RevokeBackDateNotAllowedForProfileException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public RevokeBackDateNotAllowedForProfileException_Exception(String message, cl.c2c.ejbca.RevokeBackDateNotAllowedForProfileException revokeBackDateNotAllowedForProfileException) {
        super(message);
        this.revokeBackDateNotAllowedForProfileException = revokeBackDateNotAllowedForProfileException;
    }

    public RevokeBackDateNotAllowedForProfileException_Exception(String message, cl.c2c.ejbca.RevokeBackDateNotAllowedForProfileException revokeBackDateNotAllowedForProfileException, Throwable cause) {
        super(message, cause);
        this.revokeBackDateNotAllowedForProfileException = revokeBackDateNotAllowedForProfileException;
    }

    public cl.c2c.ejbca.RevokeBackDateNotAllowedForProfileException getFaultInfo() {
        return this.revokeBackDateNotAllowedForProfileException;
    }
}
