
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.696-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "UserDoesntFullfillEndEntityProfile", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class UserDoesntFullfillEndEntityProfile_Exception extends Exception {
    
    private cl.c2c.ejbca.UserDoesntFullfillEndEntityProfile userDoesntFullfillEndEntityProfile;

    public UserDoesntFullfillEndEntityProfile_Exception() {
        super();
    }
    
    public UserDoesntFullfillEndEntityProfile_Exception(String message) {
        super(message);
    }
    
    public UserDoesntFullfillEndEntityProfile_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public UserDoesntFullfillEndEntityProfile_Exception(String message, cl.c2c.ejbca.UserDoesntFullfillEndEntityProfile userDoesntFullfillEndEntityProfile) {
        super(message);
        this.userDoesntFullfillEndEntityProfile = userDoesntFullfillEndEntityProfile;
    }

    public UserDoesntFullfillEndEntityProfile_Exception(String message, cl.c2c.ejbca.UserDoesntFullfillEndEntityProfile userDoesntFullfillEndEntityProfile, Throwable cause) {
        super(message, cause);
        this.userDoesntFullfillEndEntityProfile = userDoesntFullfillEndEntityProfile;
    }

    public cl.c2c.ejbca.UserDoesntFullfillEndEntityProfile getFaultInfo() {
        return this.userDoesntFullfillEndEntityProfile;
    }
}
