
package cl.c2c.ejbca;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.6
 * 2021-02-10T23:01:14.679-03:00
 * Generated source version: 2.5.6
 */

@WebFault(name = "WaitingForApprovalException", targetNamespace = "http://ws.protocol.core.ejbca.org/")
public class WaitingForApprovalException_Exception extends Exception {
    
    private cl.c2c.ejbca.WaitingForApprovalException waitingForApprovalException;

    public WaitingForApprovalException_Exception() {
        super();
    }
    
    public WaitingForApprovalException_Exception(String message) {
        super(message);
    }
    
    public WaitingForApprovalException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WaitingForApprovalException_Exception(String message, cl.c2c.ejbca.WaitingForApprovalException waitingForApprovalException) {
        super(message);
        this.waitingForApprovalException = waitingForApprovalException;
    }

    public WaitingForApprovalException_Exception(String message, cl.c2c.ejbca.WaitingForApprovalException waitingForApprovalException, Throwable cause) {
        super(message, cause);
        this.waitingForApprovalException = waitingForApprovalException;
    }

    public cl.c2c.ejbca.WaitingForApprovalException getFaultInfo() {
        return this.waitingForApprovalException;
    }
}
